#!/usr/bin/env sh

if [ $# -eq 0 ]; then
    echo "Usage: ./build.sh <project_id>"
    exit 1
fi

PROJ=${1}

# fname="${${PROJ##*/}%.*}"
fname="${PROJ##*/}"
_fname="${fname%.*}"

cd ./site/$_fname
echo "serving `pwd`"
claat serve 